version: '2.1'

networks:
  fabric_togettoyou_network:
    name: fabric_togettoyou_network
    external: true

services:
  # 后端
  fabric-car.server: # 修改服务名
    image: togettoyou/fabric-car.server:latest # 修改镜像名
    container_name: fabric-car.server # 修改容器名
    volumes:
      - /usr/share/zoneinfo/Asia/Shanghai:/usr/share/zoneinfo/Asia/Shanghai
      - ./../network/crypto-config:/network/crypto-config
      - ./../network/data/application:/app/data
    networks:
      - fabric_togettoyou_network
  # 前端
  fabric-car.web: # 修改服务名
    image: togettoyou/fabric-car.web:latest # 修改镜像名
    container_name: fabric-car.web # 修改容器名
    ports:
      - "8000:80"
    networks:
      - fabric_togettoyou_network
